#!/usr/bin/env python3
"""Generate a bold variant of the MD_MAX72XX built-in font (firmware/src/bold_font.h).

Each glyph is emboldened by one pixel: we append a column and set
new[i] = col[i] | col[i-1] (classic shift-and-OR embolden). Vertical strokes
become 2px thick while the letters' internal gaps stay open, so it reads as a
clean bold rather than a blob. This grows every printable glyph's width by 1
(wide letters/digits 5->6, colon 2->3, ...), which is why the firmware drops the
steady sign cutoff (STATUS_STATIC_MAX_CHARS) from 5 to 4 — 5 wide bold chars no
longer fit the 32-column panel, so 5+ char signs scroll (scrolling has no width
limit). The firmware sets this face once at init and uses it for everything; the
steady clock ("H:MM") and timer ("MM:SS") still fit because the colon is narrow.

Zero-width and blank glyphs (empty cell, space) are copied unchanged so spacing
stays tight.

Source is the library's stock table (MD_MAX72xx_font.cpp, USE_NEW_FONT block). Run
after `pio run` has fetched deps. The output header is committed; regenerate only
when the library font changes.

Usage:
  python3 tools/gen_bold_font.py [path/to/MD_MAX72xx_font.cpp]
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULT_FONT = REPO / "firmware/.pio/libdeps/esp32-s3/MD_MAX72XX/src/MD_MAX72xx_font.cpp"
OUT = REPO / "firmware/src/bold_font.h"

HEADER_LEN = 7  # 'F', version=2, firstHi, firstLo, lastHi, lastLo, height


def extract_bytes(src: str) -> list[int]:
    """Flatten the USE_NEW_FONT _sysfont[] initializer into a list of byte values."""
    m = re.search(r"_sysfont\[\]\s*=\s*\{", src)
    if not m:
        sys.exit("could not find _sysfont[] initializer")
    body = src[m.end():]
    # Keep only the USE_NEW_FONT arm (drops the #else legacy table).
    body = body.split("#else", 1)[0].split("#endif", 1)[0]
    body = body.split("#if USE_NEW_FONT", 1)[-1]

    vals: list[int] = []
    for raw in body.splitlines():
        line = raw.split("//", 1)[0]  # strip trailing comment
        for tok in line.split(","):
            tok = tok.strip()
            if not tok:
                continue
            if tok in ("{", "}", "};"):
                continue
            cm = re.fullmatch(r"'(.)'", tok)  # char literal, e.g. 'F'
            if cm:
                vals.append(ord(cm.group(1)))
            elif re.fullmatch(r"\d+", tok):
                vals.append(int(tok))
            else:
                sys.exit(f"unexpected token in font table: {tok!r}")
    return vals


def embolden(vals: list[int]) -> list[int]:
    """Copy the header verbatim; widen each printable glyph by one shift-OR column."""
    out = vals[:HEADER_LEN]
    i = HEADER_LEN
    n = len(vals)
    while i < n:
        width = vals[i]
        i += 1
        cols = vals[i:i + width]
        i += width
        if width == 0 or not any(cols):  # empty cell / space: keep tight
            out.append(width)
            out.extend(cols)
            continue
        # new[k] = cols[k] | cols[k-1], for k in 0..width (cols[-1]=cols[width]=0),
        # yielding width+1 columns: a 2px-thick stroke that keeps internal gaps.
        bold = [((cols[k] if k < width else 0) | (cols[k - 1] if k > 0 else 0)) & 0xFF
                for k in range(width + 1)]
        out.append(width + 1)
        out.extend(bold)
    return out


def render(vals: list[int]) -> str:
    lines = []
    for k in range(0, len(vals), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in vals[k:k + 16])
        lines.append("  " + chunk + ",")
    body = "\n".join(lines)
    return f"""// Generated by tools/gen_bold_font.py — do not edit by hand.
// Bold variant of the MD_MAX72XX built-in font: each printable glyph widened by
// one shift-and-OR column for 2px-thick strokes. Printable glyphs are 1px wider
// than stock, which is why STATUS_STATIC_MAX_CHARS is 4 (five wide bold chars
// overflow the 32-col panel). This is the panel's only font — set once at init
// and used for everything (ambient, signs, clock, timer, setup). See
// tools/gen_bold_font.py for the how and why.
#pragma once
#include <MD_MAX72xx.h>

// const keeps this in flash-mapped .rodata on ESP32 (a non-const PROGMEM array
// would land in RAM). setFont() wants a non-const pointer but only ever reads
// the table (pgm_read_byte), so callers pass it via a const_cast.
const MD_MAX72XX::fontType_t BOLD_FONT[] PROGMEM = {{
{body}
}};
"""


def main() -> None:
    font_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_FONT
    if not font_path.exists():
        sys.exit(f"font source not found: {font_path}\nrun `pio run -d firmware` first to fetch deps")
    vals = extract_bytes(font_path.read_text())
    if vals[:2] != [ord("F"), 2]:
        sys.exit(f"unexpected font header {vals[:HEADER_LEN]} — expected v2 ('F',2,...)")
    bold = embolden(vals)
    OUT.write_text(render(bold))
    print(f"wrote {OUT} ({len(bold)} bytes, from {font_path})")


if __name__ == "__main__":
    main()
